# .golangci.yml
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*_generated.go"

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  golint:
    min-confidence: 0.8

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - gocritic
    - gocyclo
    - golint
    - goconst
    - dupl
  disable:
    - maligned   # deprecated in favor of fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: .*\.pb\.go
      linters:
        - golint
        - gocritic
        - dupl

output:
  format: colored-line-number
  sort-results: true
